#!/usr/bin/env python

from akpytemp.template import Template
import os

def generate_sources(filter_function):
    """
    Generate derived sources from template sources
    """
    for root, dirs, files in os.walk('src'):
        for file_name in files:
            if not filter_function(file_name):
                continue
            if root.startswith('src/template'):
                continue
            path = os.path.join(root, file_name)
            derived = 'derived_' + path
            try:
                Template(path=path).save(derived)
            except Exception:
                print 'Cannot generate source for "%s"' % path
                import traceback
                traceback.print_exc()

if __name__ == '__main__':
    generate_sources(lambda f: not f.startswith('_') and f.endswith('.v'))
