#!/usr/bin/env python

from akpytemp.template import Template
import os

def generate_sources(filter_function):
    """
    Generate derived sources from template sources
    """
    print '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
    print 'Generating sources...'
    log = None
    no_errs = 0
    for root, dirs, files in os.walk('src'):
        for file_name in files:
            if not filter_function(file_name):
                continue
            if root.startswith('src/template'):
                continue
            path = os.path.join(root, file_name)
            derived = 'derived_' + path
            print 'Generating "%s"' % derived
            try:
                Template(path=path).save(derived)
            except Exception:
                print '*** Cannot generate source for "%s"' % path
                import traceback
                tb = traceback.format_exc()
                if not log:
                    print '*** Log written in "generate_source.log"'
                    log = open('generate_sources.log', 'w')
                log.write(tb)
                print tb
                no_errs += 1
    if no_errs:
        print 'Done with %d errors.' % no_errs
    else:
        print 'Completed successfully.'
    print '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
    if log:
        log.close()

if __name__ == '__main__':
    generate_sources(lambda f: not f.startswith('_') and f.endswith('.v'))
