#!/usr/bin/env python

from akpytemp.template import Template
import os

def generate_sources(filter_function):
    """
    Generate derived sources from template sources
    """
    for root, dirs, files in os.walk('src'):
        for file_name in files:
            if not filter_function(file_name):
                continue
            path = os.path.join(root, file_name)
            derived = 'derived_' + path
            Template(path=path).save(derived)

if __name__ == '__main__':
    generate_sources(lambda f: f.endswith('.v'))
