#!/bin/sh
scons pg_test
if [ ! $? -eq 0 ]; then
    exit(-1);
fi
vvp -M vpi_pyeval/build/vpi_pyeval -m pyeval build/pg_test.vvp -lxt2
gtkwave -o build/processing_test.v.lxt \
        test/processing_test_wave.gtkw
