// vim:ft=verilog:fileencoding=utf-8
// Source: {# parent().parent().name() #}
// Folder: {# parent().parent().dir() #}
// Author: Xitong Gao
// Generated on: {# from datetime import datetime #}{# datetime.now() #}
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// This file is automatically generated with akpytemp, please do not modify.
// The source code is best viewed when typesetted with minted package
// using $\LaTeX$.
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
